# Reference
# 

filebeat.config.modules:  
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true  
  reload.period: 10s


filebeat.inputs:
- type: log  
  enabled: true 
  paths:    
    - /var/log/*.log

  
output.elasticsearch:  
  hosts: ["192.168.33.10:9200"]


setup.kibana:  
  host: "192.168.33.10:5601"  
  username: vagrant  
  password: vagrant
  setup.dashboards.enabled: true
  setup.ilm.enabled: false