---
  - hosts: all
    become: yes
    gather_facts: no

    tasks:
  
    - name: Import APT Keys
      apt_key:
        state: present
        url: "{{ item }}"
      loop:
        - https://artifacts.elastic.co/GPG-KEY-elasticsearch
        - https://packages.microsoft.com/keys/microsoft.asc
      retries: 5
#    - name: Add EPEL Repository
#      yum:
#        name: epel-release


    - name: Add Microsoft Repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/debian/10/prod/ buster main
        state: present
        update_cache: yes
#        description: Microsoft Repo for RHEL-based
#        enabled: yes
#        gpgcheck: yes
#        baseurl: https://packages.microsoft.com/rhel/7/prod/
#        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        filename: packages-microsoft-prod

    - name: Clean Cache
      command: apt-get clean

    - name: Refresh apt-cache
      command: apt-get update

    - name: Install System Tools
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ufw
          - vim
          - nano
          - tmux
          - git
          - wget
          - golang

    - name: Prep to start services
      command: systemctl daemon-reload

    - name: Start Firewalld Service
      command: systemctl start ufw

#    - name: Start Firewalld Service
#      systemd:
#        name: firewalld
#        state: started
#        enabled: yes



####################################
# Install XCFE

#    - name: Install X Window System
#      command: yum groupinstall "X Window System" -y

    - name: Install XFCE 4
      apt:
        name: xfce4
        state: present

#    - name: Install XFCE
#      command: yum groupinstall "Xfce" -y

#    - name: Set Graphic Target
#      file:
#        src: /usr/lib/systemd/system/graphical.target
#        dest: /etc/systemd/system/default.target
#        state: link

    - name: Install XRDP
      apt:
        name: xrdp
        state: present

    - name: Add XRDP user to SSL-cert group
      command: adduser xrdp ssl-cert


#    - name: Reboot to set graphical target
#      reboot:
#        reboot_timeout: 300

####################################
# Operator 
    - name: Add Pneuma Firewall Rule
      ufw:
         rule: allow
         port: '2323'
         proto: tcp
         state: enabled

#    - name: Install XRDP
#      yum:
#        name: xrdp
#        state: present

    - name: Add XRDP rule
      ufw:
         rule: allow
         port: '3389'
         proto: tcp
         state: enabled

    - name: Add SSH Rule for Vagrant
      ufw:
         rule: allow
         port: '22'
         proto: tcp
         state: enabled


    - name: Reload
      command: systemctl daemon-reload

    - name: Start XRDP Service
      command: systemctl enable xrdp


###################################
# Powershell
###################################

    - name: Install Powershell
      apt:
        name: powershell
        state: present

    - name: Enable Powershell Remoting
      command: pwsh -Command {Enable-PSRemoting -Force}


###################################
# SSH Configuration
###################################

    - name: Uncomment Pass Auth Yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication\s+yes'
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'

    - name: Comment out Passauth No
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication\s+no'
        line: '# PasswordAuthentication no'
        owner: root
        group: root
        mode: '0600'

    - name: Allow SSH Pubkey Auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PubkeyAuthentication\s+yes'
        line: 'PubkeyAuthentication yes'
        owner: root
        group: root
        mode: '0600'

    - name: Add PS Subsystem to PS remote over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'Subsystem powershell /usr/bin/pwsh -sshs -NoLogo'
        create: yes
        owner: root
        group: root
        mode: '0600'

    - name: Create Vagrant User SSH Directory
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        mode: '0700'

    - name: Retrieve Default Vagrant Pub Key
      command: wget --no-check-certificate https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub -O /home/vagrant/.ssh/authorized_keys

    # - name: Copy Authorizedkeys File
    #   copy:
    #     src: ./files/authorizedkeys
    #     dest: /home/vagrant/.ssh/authorizedkeys
    #     owner: vagrant
    #     group: vagrant
    #     mode: '0600'
  
    - name: Update Permissions of SSH Key
      file:
        path: /home/vagrant/.ssh/authorized_keys
        state: file
        owner: vagrant
        mode: '0600'
  
    - name: Add AuthorizedKeysFile to Config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysFile\s+\.ssh/authorized_keys'
        line: 'AuthorizedKeysFile %h/.ssh/authorized_keys'
        owner: root
        group: root
        mode: '0600'

    - name: Restart sshd service
      systemd:
        name: sshd
        state: restarted
     
